"""The one-sentence narrative shown at the top of the card.

Deterministic and offline. The sentence is assembled from the same derived
scalars the gap rules produce, so it says exactly what was detected and nothing
more — no clinical advice, no recommendation, no inference.

This was originally generated by an LLM with a templated fallback. The model
path was removed: it cost per render on a hot path, and the fallback it degraded
to was already the sentence clinicians saw in practice. Removing it also removed
the plugin's only network I/O and its only transmission of anything to a third
party.
"""

from glp1_care_gap_copilot.gaps import (
    GAP_LABS_OVERDUE,
    GAP_NO_FOLLOWUP,
    GAP_SAFETY_CHECK_DUE,
    GAP_SAFETY_REVIEW,
    GAP_STALE_WEIGHT,
    Gap,
)


def _describe(gap: Gap) -> str:
    days = gap.detail.get("days_since_last")
    if gap.key == GAP_SAFETY_REVIEW:
        labels = gap.detail.get("labels")
        signs = ", ".join(labels).lower() if isinstance(labels, list) else "warning signs"
        drop_lb, interval = gap.detail.get("drop_lb"), gap.detail.get("interval_days")
        if isinstance(drop_lb, float) and isinstance(interval, int):
            return f"{drop_lb:.0f} lb lost in {interval} days alongside {signs}"
        return f"rapid weight loss alongside {signs}"
    if gap.key == GAP_SAFETY_CHECK_DUE:
        drop_lb, interval = gap.detail.get("drop_lb"), gap.detail.get("interval_days")
        booked = gap.detail.get("followup_booked")
        where = "at the next visit" if booked else "but no visit is booked"
        if isinstance(drop_lb, float) and isinstance(interval, int):
            return (
                f"{drop_lb:.0f} lb lost in {interval} days with no safety check "
                f"on file — screen {where}"
            )
        return f"rapid weight loss with no safety check on file — screen {where}"
    if gap.key == GAP_STALE_WEIGHT:
        if isinstance(days, int):
            return f"no weight recorded in {days} days"
        return "no weight ever recorded"
    if gap.key == GAP_LABS_OVERDUE:
        missing = gap.detail.get("missing")
        names = ", ".join(missing) if isinstance(missing, list) else "expected labs"
        interval = gap.detail.get("interval_days")
        if isinstance(interval, int):
            return f"{names} not resulted in the last {interval} days"
        return f"{names} not resulted within the monitoring interval"
    if gap.key == GAP_NO_FOLLOWUP:
        horizon = gap.detail.get("horizon_days")
        if isinstance(horizon, int):
            return f"no follow-up booked in the next {horizon} days"
        return "no follow-up booked"
    return gap.label.lower()


def build_narrative(gaps: list[Gap], weeks_since_last_visit: int | None) -> str:
    """One factual sentence restating the open gaps.

    A safety signal leads with its own sentence rather than being folded into
    the monitoring list — "contact this patient" and "labs are overdue" do not
    belong in the same breath.
    """
    if not gaps:
        return "GLP-1 monitoring is up to date; no open care gaps."

    leading_keys = (GAP_SAFETY_REVIEW, GAP_SAFETY_CHECK_DUE)
    safety = [gap for gap in gaps if gap.key in leading_keys]
    routine = [gap for gap in gaps if gap.key not in leading_keys]

    prefix = ""
    if safety:
        prefix = f"SAFETY: {'; '.join(_describe(gap) for gap in safety)}. "
        if not routine:
            base = prefix.rstrip()
            if weeks_since_last_visit is not None:
                return f"{base[:-1]} (last visit {weeks_since_last_visit} weeks ago)."
            return base

    described = "; ".join(_describe(gap) for gap in routine)
    sentence = f"{prefix}Open GLP-1 monitoring gaps: {described}."
    if weeks_since_last_visit is not None:
        sentence = f"{sentence[:-1]} (last visit {weeks_since_last_visit} weeks ago)."
    return sentence
